apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-api-pipelinerun-
spec:
  # kubectl -n test create secret docker-registry demo-credentials  --docker-username=savita3020 --docker-password=12_abcdef
  serviceAccountName: cred
#  podTemplate:
#    imagePullSecrets:
#    - name: demo-credentials
  pipelineRef:
    name: build-and-deploy
  params:
    - name: deployment-name
      value: sample-app
    - name: git-url
      value: https://github.com/savitaashture/kcd-tekton-samples
    - name: IMAGE
      value: quay.io/savitaashture/kcd:latest
      #value: docker.io/savita3020/kcd:latest
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi